name:                e-juice-calc
version:             1.0.0
github:              "githubuser/e-juice-calc"
license:             GPLv2
author:              "Richard Szibele"
maintainer:          "richard@szibele.com"
copyright:           "2018 Richard Szibele"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Application to help with mixing e-juice
# category:            Program

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/e-juice-calc#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- string-conversions
- aeson
- aeson-pretty
- directory
- hsqml

library:
  source-dirs: src

executables:
  e-juice-calc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - e-juice-calc

tests:
  e-juice-calc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - e-juice-calc
